hijiyun/level_0_escape_JS

week1-1.js
✔ 문제 유형 : 기초
✔ 문제 풀이 날짜: 2024.01.19
- 나머지를 구하는 연산자인 %를 사용해서 num1에서 num2를 나눠 나머지를 구해야 겠다고 설계하였습니다
```javascript
function solution(num1, num2) {
var answer = num1 % num2;
return answer;
}
```
- 나머지 구하가 연산자 : %
=> [박지윤] 1주차 - 나머지 구하기

머쓱이보다키큰사람.js, 문자열뒤집기.js, 배열원소의길이.js, 배열자르기.js, 중복된숫자개수.js, 피자나눠먹기(1).js, 피자나눠먹기(3).js
✔ 문제 제목 : 머쓱이보다 키 큰 사람
✔ 문제 풀이 날짜: 24.02.06
- filter메소드를 사용해서 각 val값보다 작은 값의 길이를 리턴하고자 했다
```javascript
function solution(array, height) {
return array.filter((val)=> height < val).length 
}
```
---
✔ 문제 제목 : 문자열 뒤집기
✔ 문제 풀이 날짜: 24.02.06
- 문자열을 split해서 각 문자로 나눈 배열로 만든 후 배열을 뒤집는다.
- 그리고 join메소드를 사용해서 합쳐준다
```javascript
return my_string.split('').reverse().join('')
}
```
- 문자열에 바로 reverse()를 쓰면 안된다
---
✔ 문제 제목 : 배열 원소의 길이
✔ 문제 풀이 날짜: 24.02.06
- 배열안의 값들을 val로 나타내고 각각의 길이를 배열에 담는다
```javascript
function solution(strlist) {
return strlist.map((val)=>val.length)
}
```
---
✔ 문제 제목 : 배열 자르기
✔ 문제 풀이 날짜: 24.02.06
- numbers에서 slice를 작성해서 num1부터 num2까지 자른다
```javascript
function solution(numbers, num1, num2) {
return numbers.slice(num1, num2+1);
}
```
- num2에 +1을 해줘야한다 …
=> [박지윤] Week3

.prettierrc.json, x만큼간격이있는n개의숫자.js, 개미군단.js, 숫자찾기.js, 외계행성의나이.js, 치킨쿠폰.js, 팩토리얼.js, 피자나눠먹기(2).Js
✔ 문제 제목 : 개미 군단
✔ 문제 풀이 날짜: 24.02.20
- 입력된 체력(hp)을 5로 나눈 몫을 구하고, 나머지를 5로 나눈 몫을 구한 뒤 다시 3으로 나눈 몫을 구하여, 5로 나눈 몫, 3으로 나눈 몫, 그리고 남은 나머지를 1로 처리하여 최종적으로 필요한 최소한의 개수를 반환
```javascript
function solution(hp) {
let five = Math.floor(hp / 5);
let three = Math.floor((hp % 5) / 3);
let one = (hp % 5) % 3;
return five + three + one;
}
```
---
✔ 문제 제목 : 숫자 찾기
✔ 문제 풀이 날짜: 24.02.20
- 숫자를 문자열로 변환한 후, 해당 문자열에 숫자 k가 포함되어 있는지 확인
- 포함되어 있다면 숫자 k가 처음으로 나타나는 인덱스를 반환하고, 포함되어 있지 않다면 -1을 반환
```javascript
function solution(num, k) {
return [...String(num)].includes(String(k))
? [...String(num)].indexOf(String(k)) + 1
: -1;
}
```
- [...String(num)]은 숫자를 문자열로 변환한 후, 해당 문자열을 배열로 분할하는 방법입니다! 이렇게 하면 주어진 숫자를 각 자릿수로 분할하여 배열에 저장할 수 있고, 이 배열을 통해 각 자릿수에 접근할 수 있기 때문에 주어진 숫자의 각 자릿수를 쉽게 확인할 수 있습니다 !! 
예를 들어, num이 1234라면, …
=> [박지윤] 2회 1주차

2차원으로만들기.js, n의배수고르기.js, 등수매기기.js, 자릿수더하기.js, 정수내림차순으로배치하기.js, 주사위의개수.js, 중복된문자제거.js
✔ 문제 제목 : 등수 매기기
✔ 문제 풀이 날짜: 24.03.05
1. map 함수를 사용하여 각 요소의 평균을 계산
2. slice()를 사용하여 새로운 배열을 만들고, 이후 sort() 메서드를 사용하여 평균 점수를 기준으로 내림차순으로 정렬
3. map 함수를 사용하여 각 평균 점수가 정렬된 배열에서 몇 번째 위치에 있는지 찾고 1 더해주기 
```javascript
function solution(score) {
let avg = score.map((arr) => (arr[0] + arr[1]) / 2)
let sorted = avg.slice().sort((a,b) => b-a)
return avg.map((val)=>sorted.indexOf(val)+1)
}
```
- slice()를 쓰지 않아서 원본 배열인 avg 배열도 함께 정렬되었습니다 ㅜㅜ 그래서 원본 배열의 순서가 변경되었을 때 indexOf() 메서드 호출이 정렬된 그대로 나오게 되었습니다.
- sort() 함수는 원본 배열을 변경하므로, 원본 배열의 순서를 변경하지 않으려면 slice()를 사용하여 새로운 배열을 만들어야 합니다.
---
✔ 문제 제목 : 2차원으로 만들기
✔ 문제 풀이 날짜: 24.03.05
1. while 루프를 사용하여 num_list 배열이 빈 배열이 될 때까지 반복
2. splice() 메서드를 사용하여 num_list 배열에서 길이가 n인 부분 배열을 추출 -> 새로운 배열로 만들어 answer 배열에 추가
3. 이러한 과정을 반복 후, num_list 배열이 빈 배열이 되면 answer를 반환 …
=> [박지윤] 2회 3주차

프로그래머스/0/120840. 구슬을 나누는 경우의 수/README.md, 프로그래머스/0/120840. 구슬을 나누는 경우의 수/구슬을 나누는 경우의 수.js, 프로그래머스/0/120886. A로 B 만들기/A로 B 만들기.js, 프로그래머스/0/120886. A로 B 만들기/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/문자열 정렬하기 （2）.js, 프로그래머스/0/120912. 7의 개수/7의 개수.js, 프로그래머스/0/120912. 7의 개수/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/잘라서 배열로 저장하기.js, 프로그래머스/0/120922. 종이 자르기/README.md, 프로그래머스/0/120922. 종이 자르기/종이 자르기.js, 프로그래머스/1/12948. 핸드폰 번호 가리기/README.md, 프로그래머스/1/12948. 핸드폰 번호 가리기/핸드폰 번호 가리기.js
✔ 문제 제목 : 종이 자르기
✔ 문제 풀이 날짜: 2024.03.07
- 자를려는 수는 `총 칸수 - 1` 이니까 M * N을 해서 1을 빼줌
```jsx
const solution = (M, N) => M * N - 1;
```
---
✔ 문제 제목 : 문자열 정렬하기 (2)
✔ 문제 풀이 날짜: 2024.03.07
- 모두 소문자로 만든 후
- 한글자씩 나눠서 오름차순 정렬 후 다시 문자열을 합쳐줌
```jsx
const solution = my_string => my_string.toLowerCase().split("").sort().join("");
```
```jsx
function solution(s) {
return [...s.toLowerCase()].sort().join('')
}
```
---
✔ 문제 풀이 날짜: 2024.03.07
- 배열을 다 합쳐준 후 다시 한 글자씩 쪼개서
- filter 메서드로 일치하는 값을 찾음
- filter 메서드가 반환하는 값의 개수를 구함
```jsx
const solution = (array) => array.join('').split('').filter(num => num === "7").length
```
---
✔ 문제 제목 : 구슬을 나누는 경우의 수
✔ 문제 풀이 날짜: 2024.03.07
- 팩토리얼 다 구한 후 한번에 계산
```jsx
function solution(balls, share) {
let factorial = 1;
let factorial2 = 1;
let factorial3 = 1;
// n! …
```
=> [강경미] 2회 4주차

프로그래머스/0/120840. 구슬을 나누는 경우의 수/README.md, 프로그래머스/0/120840. 구슬을 나누는 경우의 수/구슬을 나누는 경우의 수.js, 프로그래머스/0/120886. A로 B 만들기/A로 B 만들기.js, 프로그래머스/0/120886. A로 B 만들기/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/문자열 정렬하기 （2）.js, 프로그래머스/0/120912. 7의 개수/7의 개수.js, 프로그래머스/0/120912. 7의 개수/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/잘라서 배열로 저장하기.js, 프로그래머스/0/120922. 종이 자르기/README.md, 프로그래머스/0/120922. 종이 자르기/종이 자르기.js, 프로그래머스/1/12948. 핸드폰 번호 가리기/README.md, 프로그래머스/1/12948. 핸드폰 번호 가리기/핸드폰 번호 가리기.js
✔ 문제 제목 : 종이 자르기
✔ 문제 풀이 날짜: 24.03.07
- 입출력 예시를 확인했을때, 가위질의 횟수는 가로 * 세로 - 1이므로 그대로 적용해서 리턴한다.
```javascript
function solution(M, N) {
return M * N - 1;
}
```
```javascript
function solution(M, N) {
return M*N-1;
}
```
- 많이 선택한 풀이방법 (내가 풀이한 방법과 같음)
- 입출력 예시를 꼼꼼히 읽어보면 쉽게 풀릴수도 있다?
---
✔ 문제 제목 : 문자열 정렬하기 (2)
✔ 문제 풀이 날짜: 24.03.07
- my_string을 `toLowerCase`를 이용해 모두 소문자로 바꾼다.
- `spread` 문법으로 펼쳐주고, `sort`로 정렬한 다음, `join`해서 리턴해준다.
```javascript
return [...(my_string.toLowerCase())].sort().join('')
}
```
```javascript
return my_string.toLowerCase().split('').sort().join('');
}
```
- 많이 선택한 풀이방법 (내가 풀이한 방법과 같음)
---
✔ 문제 풀이 날짜: 24.03.07
- array를 문자열로 바꾸고, `spread` 문법으로 펼쳐준다.
- `filter`를 사용하여 7과 같은 값만 골라낸 뒤, `length`로 길이를 …
=> [오도담] 2회 4주차

프로그래머스/0/120840. 구슬을 나누는 경우의 수/README.md, 프로그래머스/0/120840. 구슬을 나누는 경우의 수/구슬을 나누는 경우의 수.js, 프로그래머스/0/120850. 문자열 정렬하기 （1）/README.md, 프로그래머스/0/120850. 문자열 정렬하기 （1）/문자열 정렬하기 （1）.js, 프로그래머스/0/120886. A로 B 만들기/A로 B 만들기.js, 프로그래머스/0/120886. A로 B 만들기/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/문자열 정렬하기 （2）.js, 프로그래머스/0/120912. 7의 개수/7의 개수.js, 프로그래머스/0/120912. 7의 개수/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/잘라서 배열로 저장하기.js, 프로그래머스/0/120922. 종이 자르기/README.md, 프로그래머스/0/120922. 종이 자르기/종이 자르기.js, 프로그래머스/1/12948. 핸드폰 번호 가리기/README.md, 프로그래머스/1/12948. 핸드폰 번호 가리기/핸드폰 번호 가리기.js
✔ 문제 제목 : 핸드폰 번호 가리기
✔ 문제 풀이 날짜: 2024.03.12
- 배열의 뒷 4자리를 slice로 분리하고, 4자리를 제외한 앞자리들은 map 메서드를 활용해 *로 변환한다.
```javascript
function solution(phone_number) {
return answer = (phone_number.split('').slice(0, -4).map(item => "*") + phone_number.split('').slice(-4)).split(',').join('');
}
```
```javascript
const solution = n => [...n].fill("*", 0, n.length-4).join("")
```
```javascript
function hide_numbers(s){
return s.replace(/\d(?=\d{4})/g, "*");
}
```
- 왜 같은 설계로 복잡하게 풀었나 모르겠다...
---
✔ 문제 제목 : 잘라서 배열로 저장하기
✔ 문제 풀이 날짜: 2024.03.12
- slice로 자르는 것까진 생각했는데, 이후 반복문을 돌리기 어려워서 다른 사람 풀이를 참조했다.
```javascript
function solution(my_str, n) {
let res = [];
for(let i = 0; i < my_str.length; i+=n)
res.push(my_str.slice(i, i+n))
return res;
}
```
- 
- 
---
✔ 문제 풀이 날짜: 2024.03.12
- join으로 합치고, …
=> [이서인] 2회 4주차

8주차/7의개수.js, 8주차/A로B만들기.js, 8주차/구슬을나누는경우의수.js, 8주차/문자열정렬하기.js, 8주차/잘라서배열로저장하기.js, 8주차/종이자르기.js, 8주차/핸드폰번호가리기.js
✔ 문제 풀이 날짜: 24.03.12
1. 주어진 배열의 각 요소를 순회하면서 숫자를 문자열로 변환
2. 각 숫자의 문자열에서 숫자 7의 개수를 세어 총합을 구함
3. 총합을 반환
```javascript
function solution(array) {
return array.reduce((count, num) => {
return (
count +
num
.toString()
.split('')
.filter((el) => el === '7').length
);
}, 0);
}
```
---
✔ 문제 제목 : 구슬을 나누는 경우의 수
✔ 문제 풀이 날짜: 24.03.12
1. 주어진 수부터 1까지의 모든 정수를 곱한 값을 반환 (재귀 함수를 사용하여 구현)
2. 계산된 값을 정수로 반올림하여 반환 (Math.round() 함수를 사용)
```javascript
function solution(balls, share) {
const factorial = (num) => (num === 0 ? 1 : num * factorial(num - 1));
return Math.round(
factorial(balls) / factorial(balls - share) / factorial(share),
);
}
```
-  Math.round() 함수를 사용
---
✔ 문제 제목 : 문자열 정렬하기
✔ 문제 풀이 날짜: 24.03.12
1. 문자열을 소문자로 변환
2. 변환된 문자열을 배열로 분리
3. 배열을 정렬
4. 정렬된 배열을 다시 문자열로 합쳐 반환
```javascript …
```
=> [박지윤] 2회 4주차

프로그래머스/0/120840. 구슬을 나누는 경우의 수/README.md, 프로그래머스/0/120840. 구슬을 나누는 경우의 수/구슬을 나누는 경우의 수.js, 프로그래머스/0/120886. A로 B 만들기/A로 B 만들기.js, 프로그래머스/0/120886. A로 B 만들기/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/문자열 정렬하기 （2）.js, 프로그래머스/0/120912. 7의 개수/7의 개수.js, 프로그래머스/0/120912. 7의 개수/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/잘라서 배열로 저장하기.js, 프로그래머스/0/120922. 종이 자르기/README.md, 프로그래머스/0/120922. 종이 자르기/종이 자르기.js, 프로그래머스/1/12948. 핸드폰 번호 가리기/README.md, 프로그래머스/1/12948. 핸드폰 번호 가리기/핸드폰 번호 가리기.js
✔ 문제 제목 : 종이 자르기
✔ 문제 풀이 날짜 : 2024. 03. 13 
- 처음에는 하나하나 생각해서 구해봤는데 단순히 종이 전체 칸수에서 1을 줄인 값으로 계산
```javascript
function solution(M, N) {
return M * N - 1;
}
/*
function solution(M, N) {
if(M === 1 && N === 1)return 0;
let mCnt = 0;
let nCnt = 0;
for(let i = M; i > 1; i--){
mCnt++;
}
for(let i = N; i > 1; i--){
nCnt++;
}
return mCnt + nCnt * M;
}
*/
```
-
- 다른풀이가 나랑 같아서 뿌듯하다
---
✔ 문제 제목 : 문자열 정렬하기 (2)
✔ 문제 풀이 날짜 : 2024. 03. 13 
- toLowerCase()로 문자열의 모든 문자를 소문자로 변환
- 모든 문자를 배열 각 요소로 분리해서 넣고 sort()로 정렬
- join()으로 다시 붙여줌
```javascript
return [...my_string].map((el) => el.toLowerCase()).sort().join('');
}
/*
let lower = my_string.toLowerCase().split('');
lower.sort();
return lower.join('')
}
*/
```
- 다른풀이
```javascript
function …
```
=> [김진아] 2회 4주차

프로그래머스/0/120840. 구슬을 나누는 경우의 수/README.md, 프로그래머스/0/120840. 구슬을 나누는 경우의 수/구슬을 나누는 경우의 수.js, 프로그래머스/0/120886. A로 B 만들기/A로 B 만들기.js, 프로그래머스/0/120886. A로 B 만들기/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/문자열 정렬하기 （2）.js, 프로그래머스/0/120912. 7의 개수/7의 개수.js, 프로그래머스/0/120912. 7의 개수/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/README.md, 프로그래머스/0/120913. 잘라서 배열로 저장하기/잘라서 배열로 저장하기.js, 프로그래머스/0/120922. 종이 자르기/README.md, 프로그래머스/0/120922. 종이 자르기/종이 자르기.js, 프로그래머스/1/12948. 핸드폰 번호 가리기/README.md, 프로그래머스/1/12948. 핸드폰 번호 가리기/핸드폰 번호 가리기.js
✔ 문제 제목 : 종이 자르기
✔ 문제 풀이 날짜: 24.03.12
- 1 x 1 크기로 자르려고 한다
- 길이가 M인 변을 1만큼으로 자르려면 M -1만큼의 횟수가 소요 됨
- 그렇게 잘린 종이를 각각 또 길이가 N인 변을 1만큼으로 자르면 N - 1 만큼의 횟수를 곱해줘야함
```javascript
function solution(M, N) {
return (M - 1) + M * (N - 1)
}
```
- 알아보기 쉽게 알고리즘 흐름대로 작성한 채로 두었는데 해당 식을 풀어서 정리하면 조금 더 줄여서 작성할 수 있을 것 같다.
---
✔ 문제 제목 : 문자열 정렬하기(2)
✔ 문제 풀이 날짜: 24.03.12
- 문자열을 toLowerCase 메소드로 소문자로 바꿔줌
- 스프레드 사용해서 배열로 풀어준 뒤에 sort로 오름차순으로 배치해줌
- 마지막으로 Join으로 합침
```javascript
return [...my_string.toLowerCase()].sort().join('');
}
```
- toLowerCase() : 소문자로 변환
- toUpperCase() : 대문자로 변환
---
✔ 문제 풀이 날짜: 24.03.13
- 두자리수가 있어서 각각을 map으로 돌면서 split 해줌
- flat() 메소드로 평탄화를 해줌
- 해당 배열을 reduce로 돌면서 7이 등장하면 누적값에 1을 더해준다
```javascript
function solution(array) {
const arr = …
```
=> [이지수] 2회 4주차

9주차/모음제거.js, 9주차/배열회전시키기.js, 9주차/삼각형의롼성조건.js, 9주차/약수의합.js, 9주차/연속된수의합.js, 9주차/인덱스바꾸기.js, 9주차/직사각형넓이구하기.js
✔ 문제 제목 : 모음 제거
✔ 문제 풀이 날짜: 24.03.19
- 모음을 저장하는 배열 moums을 선언하고, 주어진 문자열을 순회하면서 각 문자가 모음인지 확인합니다.
- 모음이 아닌 경우에만 result 변수에 추가하여 모음을 제거한 문자열을 생성합니다.
- 최종적으로 모음이 제거된 문자열인 result를 반환합니다.
```javascript
const moums = ['a', 'e', 'i', 'o', 'u'];
let result = '';
for (let moum of my_string) {
if (!moums.includes(moum)) {
result += moum;
}
}
return result;
}
```
- 배열 메서드 includes 활용: includes 메서드를 사용하여 모음인지 확인하는 것이 코드를 간결하게 작성하였습니다. [ includes 메서드는 배열에 해당 요소가 포함되어 있는지 여부를 확인할 수 있습니다. ]
---
✔ 문제 제목 : 배열 회전 시키기 
✔ 문제 풀이 날짜: 24.03.19
'right' 방향으로 이동할 경우, 배열의 마지막 요소를 빼내어(unshift) 배열의 맨 앞에 추가(push)합니다.
그렇지 않은 경우('left'라면), 배열의 첫 번째 요소를 제거(shift)하여 배열의 마지막에 추가합니다(pop).
이동된 배열을 반환합니다.
```javascript
function solution(numbers, direction) {
if (direction === 'right') { …
```
=> [박지윤] 3회 1주차

10주차/ox퀴즈.js, 10주차/겹치는선분의길이.js, 10주차/나머지가1이되는수찾기.js, 10주차/삼각형의완성조건.js, 10주차/숨어있는숫자의덧셈.js, 10주차/영어가싫어요.js, 10주차/저주의숫자3.js
✔ 문제 제목 : 겹치는 선분의 길이
✔ 문제 풀이 날짜: 24.03.26
1. 주어진 lines 배열에서 시작과 끝을 각각 최소값(start)과 최대값(end)으로 초기화합니다.
2. start와 end 사이의 길이를 갖는 배열(lst)을 생성하고 모든 요소를 0으로 초기화합니다.
3. 각 lines의 요소에 대해 시작부터 끝까지 순회하면서 lst 배열의 해당 인덱스 값을 증가시킵니다.
4. lst 배열을 순회하면서 값이 1보다 큰 요소의 개수를 세어 겹치는 구간의 개수를 반환합니다.
```javascript
function solution(lines) {
const start = Math.min(...lines.flat());
const end = Math.max(...lines.flat());
const lst = [...Array(end - start)].fill(0);
lines.forEach((el) => {
for (let i = el[0]; i < el[1]; i++) {
lst[i - start] += 1;
}
});
return lst.reduce((a, c) => (c > 1 ? a + 1 : a), 0);
}
```
- 잘 모르겠어서 다른분의 풀이를 참고했습니다 ,, 어려웠어요 ㅠㅠ
---
✔ 문제 제목 : 나머지가 1이 되는 수 찾기
✔ 문제 풀이 날짜: 24.03.26
1. 주어진 숫자 n에 대해 2부터 시작하여 n 이전의 숫자까지 반복문을 돌며 검사합니다.
2. 각 숫자 i에 대해 n을 i로 나눈 나머지가 1인 경우, 즉 n % i === 1인 경우 해당 숫자 i를 반환합니다. …
=> [박지윤] 3회 2주차

프로그래머스/0/120846. 합성수 찾기/README.md, 프로그래머스/0/120846. 합성수 찾기/합성수 찾기.js, 프로그래머스/0/120864. 숨어있는 숫자의 덧셈 （2）/README.md, 프로그래머스/0/120864. 숨어있는 숫자의 덧셈 （2）/숨어있는 숫자의 덧셈 （2）.js, 프로그래머스/0/120887. k의 개수/README.md, 프로그래머스/0/120887. k의 개수/k의 개수.js, 프로그래머스/0/120893. 대문자와 소문자/README.md, 프로그래머스/0/120893. 대문자와 소문자/대문자와 소문자.js, 프로그래머스/0/120899. 가장 큰 수 찾기/README.md, 프로그래머스/0/120899. 가장 큰 수 찾기/가장 큰 수 찾기.js, 프로그래머스/0/120902. 문자열 계산하기/README.md, 프로그래머스/0/120902. 문자열 계산하기/문자열 계산하기.js, 프로그래머스/1/86051. 없는 숫자 더하기/README.md, 프로그래머스/1/86051. 없는 숫자 더하기/없는 숫자 더하기.js
✔ 문제 제목 : 합성수 찾기
✔ 문제 풀이 날짜: 2024.04.02
- for문으로 n까지 1씩 증가시키면서
- j도 i까지 증가, i / j의 나머지가 0이면 num을 1 증가
- j를 i까지 모두 돌았을 때 num이 3이상이라면 합성수가 되므로 total 변수를 1 증가
- total 리턴
```jsx
let total = 0;
for(let i = 1; i <= n; i++) {
let num = 0;
for(let j = 1; j <= i; j++) {
if(i % j === 0) {
num += 1;
}
}
if(num >= 3) {
total += 1;
}
}
return total;
}
```
---
✔ 문제 제목 : 대문자와 소문자
✔ 문제 풀이 날짜: 2024.03.29
- 문자열을 한글자씩 배열로 펼쳐주고
- map 메서드로 글자들을 삼항연산자를 활용해서
- str이 대문자로 변경한 값과 일치하면 소문자로, 일치하지 않으면 대문자로 변경
```jsx
return [...my_string].map(str => str === str.toUpperCase() ? str.toLowerCase() : str.toUpperCase()).join('')
}
```
```jsx
var answer = '';
for (let c of my_string) answer += c === c.toLowerCase() ? c.toUpperCase() : …
```
=> [강경미] 3회 3주차

프로그래머스/0/120846. 합성수 찾기/README.md, 프로그래머스/0/120846. 합성수 찾기/합성수 찾기.js, 프로그래머스/0/120864. 숨어있는 숫자의 덧셈 （2）/README.md, 프로그래머스/0/120864. 숨어있는 숫자의 덧셈 （2）/숨어있는 숫자의 덧셈 （2）.js, 프로그래머스/0/120887. k의 개수/README.md, 프로그래머스/0/120887. k의 개수/k의 개수.js, 프로그래머스/0/120893. 대문자와 소문자/README.md, 프로그래머스/0/120893. 대문자와 소문자/대문자와 소문자.js, 프로그래머스/0/120899. 가장 큰 수 찾기/README.md, 프로그래머스/0/120899. 가장 큰 수 찾기/가장 큰 수 찾기.js, 프로그래머스/0/120902. 문자열 계산하기/README.md, 프로그래머스/0/120902. 문자열 계산하기/문자열 계산하기.js, 프로그래머스/1/86051. 없는 숫자 더하기/README.md, 프로그래머스/1/86051. 없는 숫자 더하기/없는 숫자 더하기.js
✔ 문제 제목 : 합성수 찾기
✔ 문제 풀이 날짜 : 2024.04.02
- for()반복문을 중복으로 사용하여 반복문의 범위를 설정
- 약수의 개수를 세기 위해 count = 0을 변수로 선언
- 만약 count가 3이상 되면 answer에 1씩 추가
```javascript
for (let i = 4; i <= n; i++) {
let cnt = 0;
for (j = 1; j <= i; j++) {
if (i % j == 0) cnt++;
}
if (cnt >= 3) answer++;
}
return answer;
}
```
- 다른풀이
```javascript
var answer = 0;
for(let i = 4; i <= n; i++){
for(let j = 2; j < i; j++){
if(i % j === 0){
answer += 1;
break;
}
}
}
return answer;
}
```
```javascript
return Array(n)
.fill()
.map((_, i) => i + 1)
.filter((i) => {
let cnt = 0;
for (let j = 1; j <= i; j++) {
if (i % j === 0) cnt++;
}
return cnt >= 3;
}).length;
}
```
- 
---
✔ 문제 제목 : 대문자와 소문자
✔ 문제 풀이 날짜 : 2024.04.02
- 
```javascript
function …
```
=> [김진아] 3회 3주차

프로그래머스/0/120846. 합성수 찾기/README.md, 프로그래머스/0/120846. 합성수 찾기/합성수 찾기.js, 프로그래머스/0/120864. 숨어있는 숫자의 덧셈 （2）/README.md, 프로그래머스/0/120864. 숨어있는 숫자의 덧셈 （2）/숨어있는 숫자의 덧셈 （2）.js, 프로그래머스/0/120887. k의 개수/README.md, 프로그래머스/0/120887. k의 개수/k의 개수.js, 프로그래머스/0/120893. 대문자와 소문자/README.md, 프로그래머스/0/120893. 대문자와 소문자/대문자와 소문자.js, 프로그래머스/0/120899. 가장 큰 수 찾기/README.md, 프로그래머스/0/120899. 가장 큰 수 찾기/가장 큰 수 찾기.js, 프로그래머스/0/120902. 문자열 계산하기/README.md, 프로그래머스/0/120902. 문자열 계산하기/문자열 계산하기.js, 프로그래머스/1/86051. 없는 숫자 더하기/README.md, 프로그래머스/1/86051. 없는 숫자 더하기/없는 숫자 더하기.js
✔ 문제 제목 : 합성수 찾기
✔ 문제 풀이 날짜: 2024.04.02
- 다른 사람 풀이를 참고했습니다.
```javascript
for (let i = 1; i <= n; i++) {
let count = 0;
for (let j = 1; j <= i; j++) {
if (i % j === 0) {
count++;
}
}
if (count >= 3) answer++;
}
return answer;
}
```
- 
- 
---
✔ 문제 제목 : 대문자와 소문자
✔ 문제 풀이 날짜: 2024.04.02
- map, if문으로 요소들을 대문자, 소문자로 분류 한 뒤 각각 문제에 맞게 바꿔준다.
```javascript
return answer = [...my_string].map(item => {
if (item === item.toLowerCase())
return item.toUpperCase()
if (item === item.toUpperCase())
return item.toLowerCase()
}).join('')
}
```
- 
- 
---
✔ 문제 제목 : 가장 큰 수 찾기
✔ 문제 풀이 날짜: 2024.04.02
- slice로 배열 복사본을 만든다.
- 원본 배열을 내림차순해서 최댓값을 구한다.
```javascript
function solution(array) {
let array_copy = array.slice();
let max = array.sort((a, …
```
=> [이서인] 3회 3주차

프로그래머스/0/120846. 합성수 찾기/README.md, 프로그래머스/0/120846. 합성수 찾기/합성수 찾기.js, 프로그래머스/0/120864. 숨어있는 숫자의 덧셈 （2）/README.md, 프로그래머스/0/120864. 숨어있는 숫자의 덧셈 （2）/숨어있는 숫자의 덧셈 （2）.js, 프로그래머스/0/120887. k의 개수/README.md, 프로그래머스/0/120887. k의 개수/k의 개수.js, 프로그래머스/0/120893. 대문자와 소문자/README.md, 프로그래머스/0/120893. 대문자와 소문자/대문자와 소문자.js, 프로그래머스/0/120899. 가장 큰 수 찾기/README.md, 프로그래머스/0/120899. 가장 큰 수 찾기/가장 큰 수 찾기.js, 프로그래머스/0/120902. 문자열 계산하기/README.md, 프로그래머스/0/120902. 문자열 계산하기/문자열 계산하기.js, 프로그래머스/1/86051. 없는 숫자 더하기/README.md, 프로그래머스/1/86051. 없는 숫자 더하기/없는 숫자 더하기.js
✔ 문제 제목 : 합성수 찾기
✔ 문제 풀이 날짜: 2024.04.01
- 1부터 n까지의 숫자가 들어있는 `arr`배열 생성
- 약수의 개수를 구하는 `count` 함수 구현
- `arr` 배열을 `map` 메소드로 돌며 `count` 함수 실행 → 각 요소의 약수의 개수를 담은 배열 반환
- 반환된 배열에서 2보다 큰 갑의 요소만 `filter` 로 추출
- length 프로퍼티로 총 개수 구함
```jsx
const arr = Array(n).fill(1).map((_, idx) => idx + 1);
const count = (i) => {
let num = 0;
for (let j = 1; j <= i; j++) {
i % j === 0 ? num += 1 : null;
}
return num;
}
return arr.map((i) => count(i)).filter((i) => i > 2).length;
}
```
```jsx
```
```jsx
```
- 
- [[Array.fill.map](http://array.fill.map/)](http://Array.fill.map) 으로 원하는 배열 생성
- `Array.from(Array(n), (v,i) => i+1)` 으로 생성 가능
---
✔ 문제 제목 : 대문자와 소문자
✔ 문제 풀이 날짜: 2024.04.02
- 문자열을 스프레드 문법으로 배열로 만들어줌
- `map` 메소드로 요소마다 돌면서 소문자는 대문자로 대문자는 소문자로 바꿔줘야함
- 해당 요소에 `toUpperCase()` 메소드를 사용했을 …
=> [이지수] 3회 3주차

12주차/369게임.js, 12주차/가까운수.js, 12주차/공던지기.js, 12주차/두정수사이의합.js, 12주차/문자열정렬하기.js, 12주차/소인수분해.js, 12주차/컨트롤제트.js
✔ 문제 제목 : 369게임
✔ 문제 풀이 날짜: 2024.04.07
1. 문자열 order를 문자 단위로 분할하여 배열로 만듭니다. 이를 위해 String(order)를 사용하여 문자열을 배열로 변환합니다.
2. filter 메서드를 사용하여 배열을 순회하면서 '3', '6', '9'를 포함하는 요소만 필터링합니다. 이때 includes 메서드를 사용하여 해당 요소가 '3', '6', '9' 중 하나인지 확인합니다.
3. 필터링된 배열의 길이를 반환하여 '3', '6', '9'의 개수를 구합니다.
```javascript
function solution(order) {
return [...String(order)].filter((v) => ['3', '6', '9'].includes(v)).length;
}
```
- `[...String(order)]` => 이렇게 하면 number를 바로 배열로 변환할 수 있어서 편하다.
---
✔ 문제 제목 : 가까운 수 
✔ 문제 풀이 날짜: 2024.04.07
1. sort 메서드를 사용하여 배열을 정렬합니다. 이 때 비교 함수를 제공하여 정렬 기준을 설정합니다. 비교 함수는 두 요소의 차이의 절대값을 비교하여 정렬하고, 만약 두 요소의 차이의 절대값이 같다면 요소 자체를 비교하여 정렬합니다.
2. 두 요소의 차이의 절대값을 비교하여 정렬하는데, 이를 통해 배열이 n과 가까운 순서대로 정렬됩니다.
3. 만약 두 요소의 차이의 절대값이 같다면 요소 자체를 비교하여 정렬하는데, 이를 통해 차이의 절대값이 같을 경우 원래의 순서를 유지합니다.
4. 정렬된 배열에서 첫 …
=> [박지윤] 3회 4주차

프로그래머스/1/12917. 문자열 내림차순으로 배치하기/README.md, 프로그래머스/1/12917. 문자열 내림차순으로 배치하기/문자열 내림차순으로 배치하기.js, 프로그래머스/1/12931. 자릿수 더하기/README.md, 프로그래머스/1/12931. 자릿수 더하기/자릿수 더하기.js, 프로그래머스/1/12947. 하샤드 수/README.md, 프로그래머스/1/12947. 하샤드 수/하샤드 수.js
✔ 문제 제목 : 자릿수 더하기
✔ 문제 풀이 날짜: 24.04.21
- n을 문자열로 변환해서 `spread`문법으로 펼쳐준 뒤, `map`으로 각 요소를 숫자로 변환하여, `reduce`로 누적값을 구해 리턴한다.
```javascript
function solution(n)
{
return [...(n + '')].map((el) => Number(el)).reduce((acc, cur) => acc + cur);
}
```
```javascript
function solution(n)
{
var answer = 0;
var m=String(n);
for(var i=0; i<m.length; i++){
answer+=parseInt(m[i]);
}
return answer;
}
```
- 많이 선택한 풀이방법
--- 
✔ 문제 제목 : 하샤드 수
✔ 문제 풀이 날짜: 24.04.21
- x를 문자열로 변환해서 `spread`문법으로 펼쳐준 뒤, `reduce`로 누적값을 구해 변수 HashadNum에 저장한다.
- 삼항 연산자를 이용해서 x를 변수 HashadNum으로 나눈 나머지가 0이라면 true를, 아니라면 false를 리턴한다.
```javascript
function solution(x) {
const HashadNum = [...(x + '')].reduce((acc, cur) => +acc + +cur);
return x % HashadNum === 0 ? true : false;
}
```
```javascript
function solution(x) {
let num = x;
let …
```
=> [오도담] 4회 2주차

프로그래머스/1/12917. 문자열 내림차순으로 배치하기/README.md, 프로그래머스/1/12917. 문자열 내림차순으로 배치하기/문자열 내림차순으로 배치하기.js, 프로그래머스/1/12931. 자릿수 더하기/README.md, 프로그래머스/1/12931. 자릿수 더하기/자릿수 더하기.js, 프로그래머스/1/12947. 하샤드 수/README.md, 프로그래머스/1/12947. 하샤드 수/하샤드 수.js
✔ 문제 제목 : 자릿수 더하기
✔ 문제 풀이 날짜: 2024.04.22
- while문의 조건을 n > 0으로 둬서 1번만 돌게 한다.
```javascript
let sum = 0;
while (n > 0) {
sum += n % 10; 
n = Math.floor(n / 10); 
}
return sum;
}
```
- 
- 
--- 
✔ 문제 제목 : 문자열 내림차순으로 배치하기
✔ 문제 풀이 날짜: 2024.04.22
- s를 스프레드 문법으로 배열로 만든다.
- sort로 오름차순하고, reverse해서 내림차순을 만든다.
- join으로 배열 요소를 합친다.
```javascript
function solution(s) {
const answer = [...s].sort().reverse().join('')
return answer;
}
```
- 
- 문자열 내림차순은 sort().reverse()로 하면 된다.
--- 
✔ 문제 제목 : 하샤드 수
✔ 문제 풀이 날짜: 2024.04.22
- while문을 사용해 자릿수를 더한 수로 x를 나눈다.
```javascript
function solution(x) {
let num = 0;
let originalX = x;
while (x > 0) {
num += x % 10; 
x = Math.floor(x / 10);
}
return originalX % num == 0 ? true : false;
}
```
- 
- x를 상수로 두지 않아 일부 문제에서 실패했다.
- let은 변한다는 것을 …
=> [이서인] 4회 2주차

14주차/문자열내림차순으로배치하기.js, 14주차/자릿수더하기.js, 14주차/하샤드수.js
✔ 문제 제목 : 문자열 내림차순으로 배치 
✔ 문제 풀이 날짜: 24.04.24
1. 문자열 s를 split('') 메서드를 사용하여 각 문자로 분할합니다.
2. 분할된 문자 배열을 sort 메서드를 사용하여 정렬합니다. 이때 정렬 방식은 주어진 조건에 따라 정의됩니다.
3. sort 메서드의 비교 함수에서는 두 문자를 비교하여 역순으로 정렬합니다. 만약 a가 b보다 크면 -1을 반환하여 a가 b보다 앞에 위치하도록 합니다. 반대로 a가 b보다 작으면 1을 반환하여 a가 b보다 뒤에 위치하도록 합니다. 같은 경우에는 0을 반환하여 순서를 변경하지 않습니다.
4. 정렬된 문자 배열을 join('') 메서드를 사용하여 다시 문자열로 결합합니다.
```javascript
function solution(s) {
const sortedChars = s.split('').sort((a, b) => {
if (a > b) return -1;
if (a < b) return 1;
return 0;
});
return sortedChars.join('');
}
```
--- 
✔ 문제 제목 : 자릿수 더하기 
✔ 문제 풀이 날짜: 24.04.24
1. 숫자 n을 String 함수를 사용하여 문자열로 변환합니다.
2. 문자열로 변환된 숫자를 split('') 메서드를 사용하여 각 자리수를 배열로 분할합니다.
3. reduce 메서드를 사용하여 배열의 각 요소를 순회하면서 누적 합을 계산합니다. 초기값으로 0을 설정합니다.
4. reduce 콜백 함수에서는 누적 합에 각 자리수를 숫자로 변환한 값을 더하여 반환합니다.
5. …
=> [박지윤] 4회 2주차

프로그래머스/1/12917. 문자열 내림차순으로 배치하기/README.md, 프로그래머스/1/12917. 문자열 내림차순으로 배치하기/문자열 내림차순으로 배치하기.js, 프로그래머스/1/12931. 자릿수 더하기/README.md, 프로그래머스/1/12931. 자릿수 더하기/자릿수 더하기.js, 프로그래머스/1/12947. 하샤드 수/README.md, 프로그래머스/1/12947. 하샤드 수/하샤드 수.js
✔ 문제 제목 : 자릿수 더하기
✔ 문제 풀이 날짜 : 2024. 04.24
- type을 String으로 바꿔줌
- for 반복문을 통해 모두 더하기
- 다시 Number type으로 변환하기위해 Number()를 사용
```javascript
let str = String(n);
for (let i = 0; i < str.length; i++) {
answer += Number(str[i]);
}
return answer;
}
```
- 다른풀이
```javascript
function solution(n){
// 쉬운방법
return (n+"").split("").reduce((acc, curr) => acc + parseInt(curr), 0)
}
```
- 
--- 
✔ 문제 제목 : 하샤드 수
✔ 문제 풀이 날짜 : 2024. 04.24
- String()으로 문자열로 바꿔준 후 split("")로 배열 형태로 만듬
- 배열의 합계를 reduce() 함수를 사용
- reduce()로 낸 합계로 나누었을때 나머지가 0이면 true를 반환
```javascript
function solution(x) {
let arr = String(x).split("");
let sum = arr.reduce((a, b) => Number(a) + Number(b));
return x % sum === 0;
}
```
- 다른풀이
```javascript
function solution(x) {
let num = x;
let sum = 0;
do …
```
=> [김진아] 4회 2주차

프로그래머스/1/12918. 문자열 다루기 기본/README.md, 프로그래머스/1/12918. 문자열 다루기 기본/문자열 다루기 기본.js, 프로그래머스/1/70128. 내적/README.md, 프로그래머스/1/70128. 내적/내적.js, 프로그래머스/1/76501. 음양 더하기/README.md, 프로그래머스/1/76501. 음양 더하기/음양 더하기.js
✔ 문제 제목 : 음양 더하기
✔ 문제 풀이 날짜: 24.05.06
- 정수들의 합을 구해야하므로 absolutes에 reduce를 사용한다.
- acc는 초기값 또는 이전값이므로 그대로 사용하고, cur은 signs[index]가 true면 cur을 그대로 더하고, false라면 -cur을 더한다.
- 누적값을 리턴한다.
```javascript
function solution(absolutes, signs) {
return absolutes.reduce((acc, cur, index) => acc + (signs[index] ? cur : -cur), 0);
}
```
```javascript
function solution(absolutes, signs) {
for (let i = 0; i < absolutes.length; i++) {
if (signs[i]) {
answer += absolutes[i];
} else {
answer -= absolutes[i];
}
}
return answer;
}
```
- 많이 선택한 풀이 방법 (`for`문과 `if ...else`문 사용)
- 처음에 바로 index를 사용하는게 기억이 안났었는데, 차근차근 생각하다보니 기억남
- 손에 익지 않았다면, 생각이라도 열심히 해보자.
--- 
✔ 문제 제목 : 내적
✔ 문제 풀이 날짜: 24.05.06
- a의 인덱스와 b의 인덱스를 곱한 값을 누적해서 더해야 하므로, a에 reduce를 사용한다.
- acc는 초기값 또는 이전값이므로 그대로 사용하고, cur에 b[index]를 곱한 …
=> [오도담] 4회 3주차

15주차/내적.js, 15주차/문자열다루기.js, 15주차/음양더하기.js
✔ 문제 제목 : 내적
✔ 문제 풀이 날짜: 2024.05.07
- 두 개의 배열 a와 b가 주어지며, 각 배열의 동일한 인덱스에 위치한 요소들을 곱한 후, 그 결과들의 합을 구해야 함
- 두 배열의 각 요소들을 순차적으로 접근하면서 곱셈을 수행해야 함 => reduce 메서드를 활용
- 배열 a를 순회하면서, 현재 요소(cur)와 배열 b의 동일 인덱스에 위치한 요소를 곱한 후, 그 결과를 누적값(acc)에 더합니다. 이 과정을 배열 a의 모든 요소에 대해 반복하고, 최종 누적값을 반환
- reduce 메서드의 두 번째 인자로 0을 설정하여, 누적값의 초기값을 0으로 함
```javascript
function solution(a, b) {
return a.reduce((acc, cur, i) => acc + cur * b[i], 0);
}
```
1. 코드가 더 간결하고 읽기 쉬워, 의도를 명확하게 전달할 수 있습니다.
2. reduce 메서드는 배열의 요소를 이용해 하나의 결과값을 도출해야 하는 경우 매우 유용하게 사용될 수 있다고 느꼈습니다.
--- 
✔ 문제 제목 : 문자열 다루기
✔ 문제 풀이 날짜: 2024.05.07
- 문자열 s가 숫자로만 구성되어 있고, 그 길이가 4 또는 6인지 확인해야 함.
- isNaN 함수를 사용하여 각 문자가 숫자인지 확인해야 함
하지만 isNaN은 문자를 인자로 받을 때, 해당 문자를 숫자로 변환할 수 있는지 판별합니다. 따라서, 문자열을 배열로 변환한 후 각 요소가 숫자인지 확인하는 과정이 필요함
- split('') 메서드로 문자열을 문자의 배열로 변환한 후, …
=> [박지윤] 4회 3주차

프로그래머스/1/12918. 문자열 다루기 기본/README.md, 프로그래머스/1/12918. 문자열 다루기 기본/문자열 다루기 기본.js, 프로그래머스/1/70128. 내적/README.md, 프로그래머스/1/70128. 내적/내적.js, 프로그래머스/1/76501. 음양 더하기/README.md, 프로그래머스/1/76501. 음양 더하기/음양 더하기.js
✔ 문제 제목 : 음양 더하기
✔ 문제 풀이 날짜 : 2024. 05. 08
- sings[i] === true이면 absolutes[i]의 실제 정수가 양수, false 이면 음수
- for() 반복문에 조건문을 사용
```javascript
function solution(absolutes, signs) {
for (let i = 0; i < signs.length; i++) {
if (signs[i]) answer += absolutes[i];
else answer -= absolutes[i];
}
return answer;
}
```
- 다른풀이
```javascript
function solution(absolutes, signs) {
return absolutes.reduce((acc, val, i) => acc + (val * (signs[i] ? 1 : -1)), 0);
}
```
- 
--- 
✔ 문제 제목 : 내적
✔ 문제 풀이 날짜 : 2024. 05. 08
- for 반복문 사용
```javascript
function solution(a, b) {
for (let i = 0; i < a.length; i++) {
answer += a[i] * b[i];
}
return answer;
}
```
- 다른풀이
```javascript
function solution(a, b) {
return a.reduce((acc, _, i) => acc += a[i] * b[i], 0);
}
```
- 
--- 
✔ 문제 제목 : 문자열 다루기 …
=> [김진아] 4회 3주차

프로그래머스/1/12918. 문자열 다루기 기본/README.md, 프로그래머스/1/12918. 문자열 다루기 기본/문자열 다루기 기본.js, 프로그래머스/1/70128. 내적/README.md, 프로그래머스/1/70128. 내적/내적.js, 프로그래머스/1/76501. 음양 더하기/README.md, 프로그래머스/1/76501. 음양 더하기/음양 더하기.js
✔ 문제 제목 : 음양 더하기
✔ 문제 풀이 날짜: 24.05.07
- for문을 돌면서 signs 배열의 인자값이 true이면 같은 인덱스의 absolutes 배열 값을 그대로 반환하고,
- false면 -1을 곱해주어서 음수로 처리해서 배열을 만든 뒤 reduce로 누산값을 구해준다
```javascript
function solution(absolutes, signs) {
let arr = []
for (let i = 0; i < absolutes.length; i++) {
if (signs[i]) {
arr.push(absolutes[i])
} else {
arr.push(-1 * absolutes[i])
}
}
return arr.reduce((acc, cur) => acc + cur, 0);
}
```
- 
- 
--- 
✔ 문제 제목 : 내적
✔ 문제 풀이 날짜: 24.05.08
- for문을 돌면서 요구사항에 맞는 배열을 만들고
- reduce를 사용해서 누산값을 구한다
```javascript
function solution(a, b) {
let arr = []
for (let i = 0; i < a.length; i++) {
arr.push(a[i]*b[i])
}
return arr.reduce((acc, cur) => acc + cur, 0)
}
```
- 
- 
--- 
✔ 문제 제목 : 문자열 다루기 기본
✔ 문제 풀이 날짜: 24.05.08
- 문자열 s의 길이가 4이거나 6인 경우를 우선 제한하고
- 문자열내에 map을 돌려서 Number를 사용해서 바꿔준 뒤,
- 모든 인수가 …
=> [이지수] 4회 3주차

16주차/부족한금액계산하기.js, 16주차/예산.js, 16주차/최대공약수와최소공배수.js
✔ 문제 제목 : 부족한 금액 계산하기
✔ 문제 풀이 날짜: 24.05.13
- 등차수열의 합 공식을 사용하여 총 가격을 계산
- 공식은 n * (first_term + last_term) / 2
- 여기서 n은 항의 수, first_term은 첫 번째 항, last_term은 마지막 항
- 총 금액은 count * (price + price * count) / 2로 계산
```javascript
function solution(price, money, count) {
let finalPrice = (count * (price + price * count)) / 2;
return Math.max(0, finalPrice - money);
}
```
```javascript
function solution(price, money, count) {
let finalPrice = 0;
for (let i = 1; i <= count; i++) {
finalPrice += price * i;
}
return money > finalPrice ? 0 : finalPrice - money;
}
```
- Math.max(0, finalPrice - money)를 사용하여 부족한 금액이 음수가 되는 경우를 예외처리하여 안정성을 높였어요 !!
--- 
✔ 문제 제목 : 예산
✔ 문제 풀이 날짜: 24.05.13
- 가장 많은 부서를 지원하기 위해서는 가장 적은 예산을 요구하는 부서부터 지원 -> 때문에 먼저 주어진 예산 요청 배열을 오름차순으로 정렬
- reduce 함수를 사용하여 배열을 순회하면서, 각 단계에서 현재까지 …
=> [박지윤] 4회 4주차 
